# Generated by Django 6.0.2 on 2026-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSeparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título da Música')),
                ('original_audio', models.FileField(upload_to='uploads/originals/', verbose_name='Arquivo de Áudio')),
                ('vocals_file', models.FileField(blank=True, null=True, upload_to='uploads/separated/')),
                ('drums_file', models.FileField(blank=True, null=True, upload_to='uploads/separated/')),
                ('bass_file', models.FileField(blank=True, null=True, upload_to='uploads/separated/')),
                ('other_file', models.FileField(blank=True, null=True, upload_to='uploads/separated/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Erro')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
