# Generated by Django 6.0.2 on 2026-02-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioseparation',
            name='guitar_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AddField(
            model_name='audioseparation',
            name='piano_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/separated/'),
        ),
    ]
