# Generated by Django 6.0.3 on 2026-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separator', '0002_audioseparation_guitar_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioseparation',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do YouTube'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='original_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/originals/', verbose_name='Arquivo de Áudio'),
        ),
    ]
