# Generated by Django 6.0.3 on 2026-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separator', '0003_audioseparation_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioseparation',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='bass_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='drums_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='guitar_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='original_audio',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/originals/', verbose_name='Arquivo de Áudio'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='other_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='piano_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
        migrations.AlterField(
            model_name='audioseparation',
            name='vocals_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/separated/'),
        ),
    ]
